/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";

export interface TestAsyncDecryptInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "callbackAddress"
      | "callbackAddresses"
      | "callbackBool"
      | "callbackBoolInfinite"
      | "callbackBoolTrustless"
      | "callbackBytes256"
      | "callbackMixed"
      | "callbackMixedBytes256"
      | "callbackUint16"
      | "callbackUint32"
      | "callbackUint4"
      | "callbackUint64"
      | "callbackUint8"
      | "latestRequestID"
      | "requestAddress"
      | "requestBool"
      | "requestBoolAboveDelay"
      | "requestBoolInfinite"
      | "requestBoolTrustless"
      | "requestEbytes256NonTrivial"
      | "requestFakeAddress"
      | "requestFakeBool"
      | "requestFakeUint16"
      | "requestFakeUint32"
      | "requestFakeUint4"
      | "requestFakeUint64"
      | "requestFakeUint8"
      | "requestMixed"
      | "requestMixedBytes256"
      | "requestSeveralAddresses"
      | "requestUint16"
      | "requestUint32"
      | "requestUint4"
      | "requestUint64"
      | "requestUint64NonTrivial"
      | "requestUint8"
      | "yAddress"
      | "yAddress2"
      | "yBool"
      | "yBytes256"
      | "yUint16"
      | "yUint32"
      | "yUint4"
      | "yUint64"
      | "yUint64_2"
      | "yUint64_3"
      | "yUint8"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "callbackAddress",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "callbackAddresses",
    values: [BigNumberish, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "callbackBool",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "callbackBoolInfinite",
    values: [BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "callbackBoolTrustless",
    values: [BigNumberish, boolean, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "callbackBytes256",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "callbackMixed",
    values: [
      BigNumberish,
      boolean,
      boolean,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      AddressLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "callbackMixedBytes256",
    values: [BigNumberish, boolean, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "callbackUint16",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "callbackUint32",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "callbackUint4",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "callbackUint64",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "callbackUint8",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "latestRequestID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestBool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestBoolAboveDelay",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestBoolInfinite",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestBoolTrustless",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestEbytes256NonTrivial",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requestFakeAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestFakeBool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestFakeUint16",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestFakeUint32",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestFakeUint4",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestFakeUint64",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestFakeUint8",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestMixed",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "requestMixedBytes256",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requestSeveralAddresses",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestUint16",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestUint32",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "requestUint4",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestUint64",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "requestUint64NonTrivial",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "requestUint8",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "yAddress", values?: undefined): string;
  encodeFunctionData(functionFragment: "yAddress2", values?: undefined): string;
  encodeFunctionData(functionFragment: "yBool", values?: undefined): string;
  encodeFunctionData(functionFragment: "yBytes256", values?: undefined): string;
  encodeFunctionData(functionFragment: "yUint16", values?: undefined): string;
  encodeFunctionData(functionFragment: "yUint32", values?: undefined): string;
  encodeFunctionData(functionFragment: "yUint4", values?: undefined): string;
  encodeFunctionData(functionFragment: "yUint64", values?: undefined): string;
  encodeFunctionData(functionFragment: "yUint64_2", values?: undefined): string;
  encodeFunctionData(functionFragment: "yUint64_3", values?: undefined): string;
  encodeFunctionData(functionFragment: "yUint8", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "callbackAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "callbackAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "callbackBool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "callbackBoolInfinite",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "callbackBoolTrustless",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "callbackBytes256",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "callbackMixed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "callbackMixedBytes256",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "callbackUint16",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "callbackUint32",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "callbackUint4",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "callbackUint64",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "callbackUint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "latestRequestID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestBool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestBoolAboveDelay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestBoolInfinite",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestBoolTrustless",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestEbytes256NonTrivial",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestFakeAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestFakeBool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestFakeUint16",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestFakeUint32",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestFakeUint4",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestFakeUint64",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestFakeUint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestMixed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestMixedBytes256",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestSeveralAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestUint16",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestUint32",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestUint4",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestUint64",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestUint64NonTrivial",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestUint8",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "yAddress", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "yAddress2", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "yBool", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "yBytes256", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "yUint16", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "yUint32", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "yUint4", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "yUint64", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "yUint64_2", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "yUint64_3", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "yUint8", data: BytesLike): Result;
}

export interface TestAsyncDecrypt extends BaseContract {
  connect(runner?: ContractRunner | null): TestAsyncDecrypt;
  waitForDeployment(): Promise<this>;

  interface: TestAsyncDecryptInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  callbackAddress: TypedContractMethod<
    [arg0: BigNumberish, decryptedInput: AddressLike],
    [string],
    "nonpayable"
  >;

  callbackAddresses: TypedContractMethod<
    [
      arg0: BigNumberish,
      decryptedInput1: AddressLike,
      decryptedInput2: AddressLike
    ],
    [string],
    "nonpayable"
  >;

  callbackBool: TypedContractMethod<
    [arg0: BigNumberish, decryptedInput: boolean],
    [boolean],
    "nonpayable"
  >;

  callbackBoolInfinite: TypedContractMethod<
    [arg0: BigNumberish, decryptedInput: boolean],
    [boolean],
    "nonpayable"
  >;

  callbackBoolTrustless: TypedContractMethod<
    [requestID: BigNumberish, decryptedInput: boolean, signatures: BytesLike[]],
    [boolean],
    "nonpayable"
  >;

  callbackBytes256: TypedContractMethod<
    [arg0: BigNumberish, decryptedInput: BytesLike],
    [string],
    "nonpayable"
  >;

  callbackMixed: TypedContractMethod<
    [
      requestID: BigNumberish,
      decBool_1: boolean,
      decBool_2: boolean,
      decUint4: BigNumberish,
      decUint8: BigNumberish,
      decUint16: BigNumberish,
      decUint32: BigNumberish,
      decUint64_1: BigNumberish,
      decUint64_2: BigNumberish,
      decUint64_3: BigNumberish,
      decAddress: AddressLike
    ],
    [bigint],
    "nonpayable"
  >;

  callbackMixedBytes256: TypedContractMethod<
    [
      arg0: BigNumberish,
      decBool: boolean,
      decAddress: AddressLike,
      bytesRes: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  callbackUint16: TypedContractMethod<
    [arg0: BigNumberish, decryptedInput: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  callbackUint32: TypedContractMethod<
    [requestID: BigNumberish, decryptedInput: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  callbackUint4: TypedContractMethod<
    [arg0: BigNumberish, decryptedInput: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  callbackUint64: TypedContractMethod<
    [arg0: BigNumberish, decryptedInput: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  callbackUint8: TypedContractMethod<
    [arg0: BigNumberish, decryptedInput: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  latestRequestID: TypedContractMethod<[], [bigint], "view">;

  requestAddress: TypedContractMethod<[], [void], "nonpayable">;

  requestBool: TypedContractMethod<[], [void], "nonpayable">;

  requestBoolAboveDelay: TypedContractMethod<[], [void], "nonpayable">;

  requestBoolInfinite: TypedContractMethod<[], [void], "nonpayable">;

  requestBoolTrustless: TypedContractMethod<[], [void], "nonpayable">;

  requestEbytes256NonTrivial: TypedContractMethod<
    [inputHandle: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  requestFakeAddress: TypedContractMethod<[], [void], "nonpayable">;

  requestFakeBool: TypedContractMethod<[], [void], "nonpayable">;

  requestFakeUint16: TypedContractMethod<[], [void], "nonpayable">;

  requestFakeUint32: TypedContractMethod<[], [void], "nonpayable">;

  requestFakeUint4: TypedContractMethod<[], [void], "nonpayable">;

  requestFakeUint64: TypedContractMethod<[], [void], "nonpayable">;

  requestFakeUint8: TypedContractMethod<[], [void], "nonpayable">;

  requestMixed: TypedContractMethod<
    [input1: BigNumberish, input2: BigNumberish],
    [void],
    "nonpayable"
  >;

  requestMixedBytes256: TypedContractMethod<
    [inputHandle: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  requestSeveralAddresses: TypedContractMethod<[], [void], "nonpayable">;

  requestUint16: TypedContractMethod<[], [void], "nonpayable">;

  requestUint32: TypedContractMethod<
    [input1: BigNumberish, input2: BigNumberish],
    [void],
    "nonpayable"
  >;

  requestUint4: TypedContractMethod<[], [void], "nonpayable">;

  requestUint64: TypedContractMethod<[], [void], "nonpayable">;

  requestUint64NonTrivial: TypedContractMethod<
    [inputHandle: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  requestUint8: TypedContractMethod<[], [void], "nonpayable">;

  yAddress: TypedContractMethod<[], [string], "view">;

  yAddress2: TypedContractMethod<[], [string], "view">;

  yBool: TypedContractMethod<[], [boolean], "view">;

  yBytes256: TypedContractMethod<[], [string], "view">;

  yUint16: TypedContractMethod<[], [bigint], "view">;

  yUint32: TypedContractMethod<[], [bigint], "view">;

  yUint4: TypedContractMethod<[], [bigint], "view">;

  yUint64: TypedContractMethod<[], [bigint], "view">;

  yUint64_2: TypedContractMethod<[], [bigint], "view">;

  yUint64_3: TypedContractMethod<[], [bigint], "view">;

  yUint8: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "callbackAddress"
  ): TypedContractMethod<
    [arg0: BigNumberish, decryptedInput: AddressLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "callbackAddresses"
  ): TypedContractMethod<
    [
      arg0: BigNumberish,
      decryptedInput1: AddressLike,
      decryptedInput2: AddressLike
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "callbackBool"
  ): TypedContractMethod<
    [arg0: BigNumberish, decryptedInput: boolean],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "callbackBoolInfinite"
  ): TypedContractMethod<
    [arg0: BigNumberish, decryptedInput: boolean],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "callbackBoolTrustless"
  ): TypedContractMethod<
    [requestID: BigNumberish, decryptedInput: boolean, signatures: BytesLike[]],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "callbackBytes256"
  ): TypedContractMethod<
    [arg0: BigNumberish, decryptedInput: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "callbackMixed"
  ): TypedContractMethod<
    [
      requestID: BigNumberish,
      decBool_1: boolean,
      decBool_2: boolean,
      decUint4: BigNumberish,
      decUint8: BigNumberish,
      decUint16: BigNumberish,
      decUint32: BigNumberish,
      decUint64_1: BigNumberish,
      decUint64_2: BigNumberish,
      decUint64_3: BigNumberish,
      decAddress: AddressLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "callbackMixedBytes256"
  ): TypedContractMethod<
    [
      arg0: BigNumberish,
      decBool: boolean,
      decAddress: AddressLike,
      bytesRes: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "callbackUint16"
  ): TypedContractMethod<
    [arg0: BigNumberish, decryptedInput: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "callbackUint32"
  ): TypedContractMethod<
    [requestID: BigNumberish, decryptedInput: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "callbackUint4"
  ): TypedContractMethod<
    [arg0: BigNumberish, decryptedInput: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "callbackUint64"
  ): TypedContractMethod<
    [arg0: BigNumberish, decryptedInput: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "callbackUint8"
  ): TypedContractMethod<
    [arg0: BigNumberish, decryptedInput: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "latestRequestID"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "requestAddress"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestBool"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestBoolAboveDelay"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestBoolInfinite"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestBoolTrustless"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestEbytes256NonTrivial"
  ): TypedContractMethod<
    [inputHandle: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requestFakeAddress"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestFakeBool"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestFakeUint16"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestFakeUint32"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestFakeUint4"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestFakeUint64"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestFakeUint8"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestMixed"
  ): TypedContractMethod<
    [input1: BigNumberish, input2: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requestMixedBytes256"
  ): TypedContractMethod<
    [inputHandle: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requestSeveralAddresses"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestUint16"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestUint32"
  ): TypedContractMethod<
    [input1: BigNumberish, input2: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requestUint4"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestUint64"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestUint64NonTrivial"
  ): TypedContractMethod<
    [inputHandle: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requestUint8"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "yAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "yAddress2"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "yBool"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "yBytes256"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "yUint16"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "yUint32"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "yUint4"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "yUint64"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "yUint64_2"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "yUint64_3"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "yUint8"
  ): TypedContractMethod<[], [bigint], "view">;

  filters: {};
}
