/* Autogenerated file. Do not edit manually. */

/* tslint:disable */

/* eslint-disable */
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";

export interface FhevmLibInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "cast"
      | "fheAdd"
      | "fheArrayEq"
      | "fheBitAnd"
      | "fheBitOr"
      | "fheBitXor"
      | "fheDiv"
      | "fheEq"
      | "fheGe"
      | "fheGt"
      | "fheIfThenElse"
      | "fheLe"
      | "fheLt"
      | "fheMax"
      | "fheMin"
      | "fheMul"
      | "fheNe"
      | "fheNeg"
      | "fheNot"
      | "fhePubKey"
      | "fheRand"
      | "fheRandBounded"
      | "fheRem"
      | "fheRotl"
      | "fheRotr"
      | "fheShl"
      | "fheShr"
      | "fheSub"
      | "trivialEncrypt"
      | "verifyCiphertext"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "cast",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "fheAdd",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "fheArrayEq",
    values: [BigNumberish[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "fheBitAnd",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "fheBitOr",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "fheBitXor",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "fheDiv",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "fheEq",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "fheGe",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "fheGt",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "fheIfThenElse",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fheLe",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "fheLt",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "fheMax",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "fheMin",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "fheMul",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "fheNe",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "fheNeg",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fheNot",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fhePubKey",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "fheRand",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fheRandBounded",
    values: [BigNumberish, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fheRem",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "fheRotl",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "fheRotr",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "fheShl",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "fheShr",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "fheSub",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "trivialEncrypt",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyCiphertext",
    values: [BytesLike, AddressLike, AddressLike, BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "cast", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fheAdd", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fheArrayEq", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fheBitAnd", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fheBitOr", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fheBitXor", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fheDiv", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fheEq", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fheGe", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fheGt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "fheIfThenElse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fheLe", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fheLt", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fheMax", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fheMin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fheMul", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fheNe", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fheNeg", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fheNot", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fhePubKey", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fheRand", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "fheRandBounded",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fheRem", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fheRotl", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fheRotr", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fheShl", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fheShr", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "fheSub", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "trivialEncrypt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyCiphertext",
    data: BytesLike
  ): Result;
}

export interface FhevmLib extends BaseContract {
  connect(runner?: ContractRunner | null): FhevmLib;
  waitForDeployment(): Promise<this>;

  interface: FhevmLibInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  cast: TypedContractMethod<
    [ct: BigNumberish, toType: BytesLike],
    [bigint],
    "view"
  >;

  fheAdd: TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish, scalarByte: BytesLike],
    [bigint],
    "view"
  >;

  fheArrayEq: TypedContractMethod<
    [lhs: BigNumberish[], rhs: BigNumberish[]],
    [bigint],
    "view"
  >;

  fheBitAnd: TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish, scalarByte: BytesLike],
    [bigint],
    "view"
  >;

  fheBitOr: TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish, scalarByte: BytesLike],
    [bigint],
    "view"
  >;

  fheBitXor: TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish, scalarByte: BytesLike],
    [bigint],
    "view"
  >;

  fheDiv: TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish, scalarByte: BytesLike],
    [bigint],
    "view"
  >;

  fheEq: TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish, scalarByte: BytesLike],
    [bigint],
    "view"
  >;

  fheGe: TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish, scalarByte: BytesLike],
    [bigint],
    "view"
  >;

  fheGt: TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish, scalarByte: BytesLike],
    [bigint],
    "view"
  >;

  fheIfThenElse: TypedContractMethod<
    [control: BigNumberish, ifTrue: BigNumberish, ifFalse: BigNumberish],
    [bigint],
    "view"
  >;

  fheLe: TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish, scalarByte: BytesLike],
    [bigint],
    "view"
  >;

  fheLt: TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish, scalarByte: BytesLike],
    [bigint],
    "view"
  >;

  fheMax: TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish, scalarByte: BytesLike],
    [bigint],
    "view"
  >;

  fheMin: TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish, scalarByte: BytesLike],
    [bigint],
    "view"
  >;

  fheMul: TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish, scalarByte: BytesLike],
    [bigint],
    "view"
  >;

  fheNe: TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish, scalarByte: BytesLike],
    [bigint],
    "view"
  >;

  fheNeg: TypedContractMethod<[ct: BigNumberish], [bigint], "view">;

  fheNot: TypedContractMethod<[ct: BigNumberish], [bigint], "view">;

  fhePubKey: TypedContractMethod<[fromLib: BytesLike], [string], "view">;

  fheRand: TypedContractMethod<
    [randType: BytesLike, seed: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  fheRandBounded: TypedContractMethod<
    [upperBound: BigNumberish, randType: BytesLike, seed: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  fheRem: TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish, scalarByte: BytesLike],
    [bigint],
    "view"
  >;

  fheRotl: TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish, scalarByte: BytesLike],
    [bigint],
    "view"
  >;

  fheRotr: TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish, scalarByte: BytesLike],
    [bigint],
    "view"
  >;

  fheShl: TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish, scalarByte: BytesLike],
    [bigint],
    "view"
  >;

  fheShr: TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish, scalarByte: BytesLike],
    [bigint],
    "view"
  >;

  fheSub: TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish, scalarByte: BytesLike],
    [bigint],
    "view"
  >;

  trivialEncrypt: TypedContractMethod<
    [ct: BigNumberish, toType: BytesLike],
    [bigint],
    "view"
  >;

  verifyCiphertext: TypedContractMethod<
    [
      inputHandle: BytesLike,
      callerAddress: AddressLike,
      contractAddress: AddressLike,
      inputProof: BytesLike,
      inputType: BytesLike
    ],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "cast"
  ): TypedContractMethod<
    [ct: BigNumberish, toType: BytesLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "fheAdd"
  ): TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish, scalarByte: BytesLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "fheArrayEq"
  ): TypedContractMethod<
    [lhs: BigNumberish[], rhs: BigNumberish[]],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "fheBitAnd"
  ): TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish, scalarByte: BytesLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "fheBitOr"
  ): TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish, scalarByte: BytesLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "fheBitXor"
  ): TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish, scalarByte: BytesLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "fheDiv"
  ): TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish, scalarByte: BytesLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "fheEq"
  ): TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish, scalarByte: BytesLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "fheGe"
  ): TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish, scalarByte: BytesLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "fheGt"
  ): TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish, scalarByte: BytesLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "fheIfThenElse"
  ): TypedContractMethod<
    [control: BigNumberish, ifTrue: BigNumberish, ifFalse: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "fheLe"
  ): TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish, scalarByte: BytesLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "fheLt"
  ): TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish, scalarByte: BytesLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "fheMax"
  ): TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish, scalarByte: BytesLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "fheMin"
  ): TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish, scalarByte: BytesLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "fheMul"
  ): TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish, scalarByte: BytesLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "fheNe"
  ): TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish, scalarByte: BytesLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "fheNeg"
  ): TypedContractMethod<[ct: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "fheNot"
  ): TypedContractMethod<[ct: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "fhePubKey"
  ): TypedContractMethod<[fromLib: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "fheRand"
  ): TypedContractMethod<
    [randType: BytesLike, seed: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "fheRandBounded"
  ): TypedContractMethod<
    [upperBound: BigNumberish, randType: BytesLike, seed: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "fheRem"
  ): TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish, scalarByte: BytesLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "fheRotl"
  ): TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish, scalarByte: BytesLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "fheRotr"
  ): TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish, scalarByte: BytesLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "fheShl"
  ): TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish, scalarByte: BytesLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "fheShr"
  ): TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish, scalarByte: BytesLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "fheSub"
  ): TypedContractMethod<
    [lhs: BigNumberish, rhs: BigNumberish, scalarByte: BytesLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "trivialEncrypt"
  ): TypedContractMethod<
    [ct: BigNumberish, toType: BytesLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "verifyCiphertext"
  ): TypedContractMethod<
    [
      inputHandle: BytesLike,
      callerAddress: AddressLike,
      contractAddress: AddressLike,
      inputProof: BytesLike,
      inputType: BytesLike
    ],
    [bigint],
    "view"
  >;

  filters: {};
}
