/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IACL__factory } from "./IACL__factory";
export { IFHEVMCoprocessor__factory } from "./IFHEVMCoprocessor__factory";
